### ISSUE TITLE
Mandatory space before :global gets removed

### ISSUE THREAD

**Issue by marcselman** [aeschli/vscode-css-formatter#3]
When using CSS Modules I sometimes use `:global` inside my CSS selector to access global class names instead of local ones.

Example:

``` css
.row :global .icon {
    border: 1px solid #ff0000;
}
```

Your formatter removes the space before `:global` which is not permitted.
