### ISSUE TITLE
break the less compilation after formatting with plugin

### ISSUE THREAD

**Issue by lucax88x** [aeschli/vscode-css-formatter#5]
using this particular css:

filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);

if you format you get a space between progid and DXImageblabla

filter: progid: DXImageTransform.Microsoft.gradient(enabled=false);

and this breaks the less compilation.

**Comment by pmanu93** [comment]
I'm having the same issue at the moment.. -.-'

**Comment by aeschli** [comment]
This seems to work now with the latest update of js-beautify. 
 ```css
 foo {

    filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
}
```

No space is inserted after `progid:` format
